title: Jayson Freitas
author: jaysonpf
email: jaysonpf@gmail.com
description:
  Jayson Freitas Page
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""
show_dir_listing : false

sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: Jayson Freitas
  tagline: Developer
  date_format: "%-d %b %Y"
  style: black
  showNav: false
  showPicker: false

  social_links:
    twitter: jaysonpf  
    github:  jaysonpf
    linkedIn: in/jaysonpf
    rss: rss



# Build settings

plugins:
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
