title: Texture Theme
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: Jayson Freitas
  tagline: Developer
  date_format: "%-d %b %Y"
  style: black
  showNav: false
  showPicker: false

  social_links:
    twitter: jaysonpf  
    github:  jaysonpf
    linkedIn: in/jaysonpf
    rss: rss



# Build settings

plugins:
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
